export {default as Home} from "./Home/Home";
export {default as Category} from "./Category/Category";
export {default as Product} from "./Product/Product";
export {default as Register} from "./Register/Register";
export {default as Login} from "./Login/Login";
export {default as Cart} from "./Cart/Cart";
export {default as Payment} from "./Payment/Payment";
export {default as Success} from "./Success/Success";
export {default as NotFound} from "./NotFound/NotFound";